# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/coding_cpp_pi/my_Project_0.10

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/coding_cpp_pi/my_Project_0.10

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/coding_cpp_pi/my_Project_0.10/CMakeFiles /home/pi/coding_cpp_pi/my_Project_0.10/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/coding_cpp_pi/my_Project_0.10/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_Project_0_10

# Build rule for target.
my_Project_0_10: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_Project_0_10
.PHONY : my_Project_0_10

# fast build rule for target.
my_Project_0_10/fast:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/build
.PHONY : my_Project_0_10/fast

GPIOHandle.o: GPIOHandle.cpp.o
.PHONY : GPIOHandle.o

# target to build an object file
GPIOHandle.cpp.o:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/GPIOHandle.cpp.o
.PHONY : GPIOHandle.cpp.o

GPIOHandle.i: GPIOHandle.cpp.i
.PHONY : GPIOHandle.i

# target to preprocess a source file
GPIOHandle.cpp.i:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/GPIOHandle.cpp.i
.PHONY : GPIOHandle.cpp.i

GPIOHandle.s: GPIOHandle.cpp.s
.PHONY : GPIOHandle.s

# target to generate assembly for a file
GPIOHandle.cpp.s:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/GPIOHandle.cpp.s
.PHONY : GPIOHandle.cpp.s

I2C_Dummy.o: I2C_Dummy.cpp.o
.PHONY : I2C_Dummy.o

# target to build an object file
I2C_Dummy.cpp.o:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/I2C_Dummy.cpp.o
.PHONY : I2C_Dummy.cpp.o

I2C_Dummy.i: I2C_Dummy.cpp.i
.PHONY : I2C_Dummy.i

# target to preprocess a source file
I2C_Dummy.cpp.i:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/I2C_Dummy.cpp.i
.PHONY : I2C_Dummy.cpp.i

I2C_Dummy.s: I2C_Dummy.cpp.s
.PHONY : I2C_Dummy.s

# target to generate assembly for a file
I2C_Dummy.cpp.s:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/I2C_Dummy.cpp.s
.PHONY : I2C_Dummy.cpp.s

LEDHandle.o: LEDHandle.cpp.o
.PHONY : LEDHandle.o

# target to build an object file
LEDHandle.cpp.o:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/LEDHandle.cpp.o
.PHONY : LEDHandle.cpp.o

LEDHandle.i: LEDHandle.cpp.i
.PHONY : LEDHandle.i

# target to preprocess a source file
LEDHandle.cpp.i:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/LEDHandle.cpp.i
.PHONY : LEDHandle.cpp.i

LEDHandle.s: LEDHandle.cpp.s
.PHONY : LEDHandle.s

# target to generate assembly for a file
LEDHandle.cpp.s:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/LEDHandle.cpp.s
.PHONY : LEDHandle.cpp.s

SPI_MCP23S17.o: SPI_MCP23S17.cpp.o
.PHONY : SPI_MCP23S17.o

# target to build an object file
SPI_MCP23S17.cpp.o:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/SPI_MCP23S17.cpp.o
.PHONY : SPI_MCP23S17.cpp.o

SPI_MCP23S17.i: SPI_MCP23S17.cpp.i
.PHONY : SPI_MCP23S17.i

# target to preprocess a source file
SPI_MCP23S17.cpp.i:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/SPI_MCP23S17.cpp.i
.PHONY : SPI_MCP23S17.cpp.i

SPI_MCP23S17.s: SPI_MCP23S17.cpp.s
.PHONY : SPI_MCP23S17.s

# target to generate assembly for a file
SPI_MCP23S17.cpp.s:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/SPI_MCP23S17.cpp.s
.PHONY : SPI_MCP23S17.cpp.s

SPI_MCP3008.o: SPI_MCP3008.cpp.o
.PHONY : SPI_MCP3008.o

# target to build an object file
SPI_MCP3008.cpp.o:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/SPI_MCP3008.cpp.o
.PHONY : SPI_MCP3008.cpp.o

SPI_MCP3008.i: SPI_MCP3008.cpp.i
.PHONY : SPI_MCP3008.i

# target to preprocess a source file
SPI_MCP3008.cpp.i:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/SPI_MCP3008.cpp.i
.PHONY : SPI_MCP3008.cpp.i

SPI_MCP3008.s: SPI_MCP3008.cpp.s
.PHONY : SPI_MCP3008.s

# target to generate assembly for a file
SPI_MCP3008.cpp.s:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/SPI_MCP3008.cpp.s
.PHONY : SPI_MCP3008.cpp.s

i2c8Bit.o: i2c8Bit.cpp.o
.PHONY : i2c8Bit.o

# target to build an object file
i2c8Bit.cpp.o:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/i2c8Bit.cpp.o
.PHONY : i2c8Bit.cpp.o

i2c8Bit.i: i2c8Bit.cpp.i
.PHONY : i2c8Bit.i

# target to preprocess a source file
i2c8Bit.cpp.i:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/i2c8Bit.cpp.i
.PHONY : i2c8Bit.cpp.i

i2c8Bit.s: i2c8Bit.cpp.s
.PHONY : i2c8Bit.s

# target to generate assembly for a file
i2c8Bit.cpp.s:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/i2c8Bit.cpp.s
.PHONY : i2c8Bit.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/my_Project_0_10.dir/build.make CMakeFiles/my_Project_0_10.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... my_Project_0_10"
	@echo "... rebuild_cache"
	@echo "... GPIOHandle.o"
	@echo "... GPIOHandle.i"
	@echo "... GPIOHandle.s"
	@echo "... I2C_Dummy.o"
	@echo "... I2C_Dummy.i"
	@echo "... I2C_Dummy.s"
	@echo "... LEDHandle.o"
	@echo "... LEDHandle.i"
	@echo "... LEDHandle.s"
	@echo "... SPI_MCP23S17.o"
	@echo "... SPI_MCP23S17.i"
	@echo "... SPI_MCP23S17.s"
	@echo "... SPI_MCP3008.o"
	@echo "... SPI_MCP3008.i"
	@echo "... SPI_MCP3008.s"
	@echo "... i2c8Bit.o"
	@echo "... i2c8Bit.i"
	@echo "... i2c8Bit.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

